#!/usr/bin/env node

var tag = process.argv[2],
    token = process.argv[3],
    http = require('https'),
    body = "",
    options = {
    host: 'api.github.com',
        headers: {
            'Authorization': 'token ' + token,
            'user-agent': 'Mozilla/5.0',
        },
        path: '/repos/gismartwaredev/smartgeomobile/releases'
    };

http.get(options, function(resp) {
    resp.setEncoding('utf8');
    resp.on('data', function(chunk) {
        body += chunk;
    });
    resp.on('end', function() {
        body = JSON.parse(body);
        for (var i = 0; i < body.length; i++) {
            if (body[i].tag_name === tag) {
                return console.log(body[i].id);
            }
            return console.log("");
        }
    });
}).on("error", function(e) {
    console.log("Got error: " + e.message);
});